### ISSUE TITLE
[FR] Implement Controls for [Raspberry Pi Camera Module 3 - imx708]

### ISSUE THREAD

**Issue by tomfrenzel** [The-EG/OctoPrint-CameraSettings#100]
Raspberry Pi Camera Module 3 (imx708 sensor)

```
{
  "wide_dynamic_range": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "grabbed"
  }
}
```

**Comment by The-EG** [comment]
This should now be in the latest release candidate. Directions for installing that can be found in the FAQ: https://github.com/The-EG/OctoPrint-CameraSettings/blob/main/docs/faq.md#how-do-i-install-the-latest-release-candidate

**Comment by tomfrenzel** [comment]
Thanks for the quick release!
Could you also add the option to manually set the focus? Because if I set it with some python script, the focus resets after each reboot of the Raspberry Pi
