### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by pjw0063** [The-EG/OctoPrint-CameraSettings#102]
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "video_b_frames": {
    "type": "int",
    "min": "0",
    "max": "4",
    "step": "1",
    "default": "0",
    "value": "0",
    "flags": "update"
  },
  "video_gop_size": {
    "type": "int",
    "min": "0",
    "max": "65535",
    "step": "1",
    "default": "30",
    "value": "30"
  },
  "video_peak_bitrate": {
    "type": "int",
    "min": "32000",
    "max": "160000000",
    "step": "100",
    "default": "2000000",
    "value": "2000000"
  },
  "sequence_header_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Separate Buffer"
      },
      {
        "value": "1",
        "desc": "Joined With 1st Frame"
      }
    ],
    "min": "0",
    "max": "1",
    "default": "1",
    "value": "1"
  },
  "maximum_bytes_in_a_slice": {
    "type": "int",
    "min": "1024",
    "max": "1024",
    "step": "1",
    "default": "1024",
    "value": "1024"
  },
  "number_of_mbs_in_a_slice": {
    "type": "int",
    "min": "1",
    "max": "300",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "slice_partitioning_method": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Single"
      },
      {
        "value": "1",
        "desc": "Max Macroblocks"
      },
      {
        "value": "2",
        "desc": "Max Bytes"
      }
    ],
    "min": "0",
    "max": "2",
    "default": "0",
    "value": "0"
  },
  "base_layer_priority_id": {
    "type": "int",
    "min": "0",
    "max": "6",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "ltr_count": {
    "type": "int",
    "min": "0",
    "max": "4",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "frame_ltr_index": {
    "type": "int",
    "min": "0",
    "max": "3",
    "step": "1",
    "default": "0",
    "value": "0",
    "flags": "execute"
  },
  "use_ltr_frames": {
    "type": "bitmask",
    "max": "0"
  },
  "intra_refresh_period": {
    "type": "int",
    "min": "0",
    "max": "36864",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "h264_i_frame_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "26",
    "value": "26"
  },
  "h264_p_frame_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "28",
    "value": "28"
  },
  "h264_b_frame_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "30",
    "value": "30"
  },
  "h264_8x8_transform_enable": {
    "type": "bool",
    "default": "1",
    "value": "1"
  },
  "h264_entropy_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "CAVLC"
      },
      {
        "value": "1",
        "desc": "CABAC"
      }
    ],
    "min": "0",
    "max": "1",
    "default": "0",
    "value": "0"
  },
  "h264_loop_filter_alpha_offset": {
    "type": "int",
    "min": "-6",
    "max": "6",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "h264_loop_filter_beta_offset": {
    "type": "int",
    "min": "-6",
    "max": "6",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "h264_loop_filter_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Enabled"
      },
      {
        "value": "1",
        "desc": "Disabled"
      },
      {
        "value": "2",
        "desc": "Disabled at Slice Boundary"
      }
    ],
    "min": "0",
    "max": "2",
    "default": "1",
    "value": "1"
  },
  "h264_i_frame_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "h264_i_frame_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "51",
    "value": "51"
  },
  "h264_p_frame_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "h264_p_frame_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "51",
    "value": "51"
  },
  "h264_b_frame_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "h264_b_frame_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "51",
    "step": "1",
    "default": "51",
    "value": "51"
  },
  "mpeg4_level": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "0"
      },
      {
        "value": "1",
        "desc": "0b"
      },
      {
        "value": "2",
        "desc": "1"
      },
      {
        "value": "3",
        "desc": "2"
      },
      {
        "value": "4",
        "desc": "3"
      },
      {
        "value": "5",
        "desc": "3b"
      },
      {
        "value": "6",
        "desc": "4"
      },
      {
        "value": "7",
        "desc": "5"
      }
    ],
    "min": "0",
    "max": "7",
    "default": "0",
    "value": "0"
  },
  "mpeg4_profile": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Simple"
      },
      {
        "value": "1",
        "desc": "Advanced Simple"
      }
    ],
    "min": "0",
    "max": "4",
    "default": "0",
    "value": "0"
  },
  "vpx_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "128",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "vpx_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "128",
    "step": "1",
    "default": "128",
    "value": "128"
  },
  "vp8_profile": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "0"
      },
      {
        "value": "1",
        "desc": "1"
      },
      {
        "value": "2",
        "desc": "2"
      },
      {
        "value": "3",
        "desc": "3"
      }
    ],
    "min": "0",
    "max": "3",
    "default": "0",
    "value": "0"
  },
  "hevc_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "hevc_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "63",
    "value": "63"
  },
  "hevc_i_frame_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "26",
    "value": "26"
  },
  "hevc_p_frame_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "28",
    "value": "28"
  },
  "hevc_b_frame_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "30",
    "value": "30"
  },
  "hevc_profile": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Main"
      },
      {
        "value": "1",
        "desc": "Main Still Picture"
      },
      {
        "value": "2",
        "desc": "Main 10"
      }
    ],
    "min": "0",
    "max": "2",
    "default": "0",
    "value": "0"
  },
  "hevc_level": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "1"
      },
      {
        "value": "1",
        "desc": "2"
      },
      {
        "value": "2",
        "desc": "2.1"
      },
      {
        "value": "3",
        "desc": "3"
      },
      {
        "value": "4",
        "desc": "3.1"
      },
      {
        "value": "5",
        "desc": "4"
      },
      {
        "value": "6",
        "desc": "4.1"
      },
      {
        "value": "7",
        "desc": "5"
      },
      {
        "value": "8",
        "desc": "5.1"
      },
      {
        "value": "9",
        "desc": "5.2"
      },
      {
        "value": "10",
        "desc": "6"
      },
      {
        "value": "11",
        "desc": "6.1"
      },
      {
        "value": "12",
        "desc": "6.2"
      }
    ],
    "min": "0",
    "max": "12",
    "default": "0",
    "value": "0"
  },
  "constant_quality": {
    "type": "int",
    "min": "0",
    "max": "100",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "frame_skip_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Disabled"
      },
      {
        "value": "2",
        "desc": "VBV/CPB Limit"
      }
    ],
    "min": "0",
    "max": "2",
    "default": "0",
    "value": "0"
  },
  "hevc_i_frame_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "hevc_i_frame_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "63",
    "value": "63"
  },
  "hevc_p_frame_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "hevc_p_frame_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "63",
    "value": "63"
  },
  "hevc_b_frame_minimum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "1",
    "value": "1"
  },
  "hevc_b_frame_maximum_qp_value": {
    "type": "int",
    "min": "1",
    "max": "63",
    "step": "1",
    "default": "63",
    "value": "63"
  },
  "hdr10_content_light_info": {
    "type": "unknown"
  },
  "hdr10_mastering_display": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment]
These should be available for testing the latest release candidate. Instructions for installing that can be found in the FAQ: https://github.com/The-EG/OctoPrint-CameraSettings/blob/main/docs/faq.md#how-do-i-install-the-latest-release-candidate
