### ISSUE TITLE
[FR] Implement Controls for Arducam B0031

### ISSUE THREAD

**Issue by wwian** [The-EG/OctoPrint-CameraSettings#103]
Camera manufacturer and model:
Arducam Lens Board OV5647 Sensor for Raspberry Pi Camera, Adjustable and Interchangeable Lens M12 Module, Focus and Angle Enhancement for Raspberry Pi 4/3/3 B+ [https://smile.amazon.com/gp/product/B013JTY8WY/]

Unknown controls information:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment]
Please update to the newest version of this plugin if you haven't already. 'Unknown' controls should already be ignored.
