### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by aslabsalbeh** [The-EG/OctoPrint-CameraSettings#104]
Hey. Under the camera controls I have two options in the drop down "cedrus" and "C922 Pro" which is my Logitech webcam. Octoprint keeps defaulting back to cedrus whenever I restart it. 

I'm using octopprint_deploy script on my orangepi LTS. Is "cedrus" supposed to be there? Thanks!

**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "hevc_slice_parameters": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  },
  "h264_sequence_parameter_set": {
    "type": "unknown"
  },
  "h264_picture_parameter_set": {
    "type": "unknown"
  },
  "h264_scaling_matrix": {
    "type": "unknown"
  },
  "h264_prediction_weight_table": {
    "type": "unknown"
  },
  "h264_slice_parameters": {
    "type": "unknown"
  },
  "h264_decode_parameters": {
    "type": "unknown"
  },
  "vp8_frame_parameters": {
    "type": "unknown"
  },
  "mpeg_2_sequence_header": {
    "type": "unknown"
  },
  "mpeg_2_picture_header": {
    "type": "unknown"
  },
  "mpeg_2_quantisation_matrices": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment]
'cedrus' is likely part of the encoding/decoding stack and can be ignored. The choice in the camera settings isn't saved, so each time you open the window it will default to the first entry, sorted alphabetically.
