### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by AlAmantea** [The-EG/OctoPrint-CameraSettings#15]
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hue_auto": {
    "type": "bool",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment]
This is now available in pre-release 0.1.1rc1.

You can get it now by changing to the Release Candidate channel for this plugin in the Software Update settings:
![image](https://user-images.githubusercontent.com/7342077/116700285-9aa9b800-a994-11eb-9e05-ddefe3552a5c.png)

After some testing, this will be released into an official release (0.1.1)

**Comment by AlAmantea** [comment]
Thanks Al Amantea  From: Taylor TalkingtonSent: Friday, April 30, 2021 8:18 AMTo: The-EG/OctoPrint-CameraSettingsCc: AlAmantea; AuthorSubject: Re: [The-EG/OctoPrint-CameraSettings] [FR] Implement Controls for [Camera Name] (#15) This is now available in pre-release 0.1.1rc1.You can get it now by changing to the Release Candidate channel for this plugin in the Software Update settings:After some testing, this will be released into an official release (0.1.1)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
