### ISSUE TITLE
[FR] Implement Controls for HD Pro Webcam C920

### ISSUE THREAD

**Issue by K1d-rue** [The-EG/OctoPrint-CameraSettings#160]
**HD Pro Webcam C920**:

**{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
})**:

**Comment by The-EG** [comment]
duplicate of #106
