### ISSUE TITLE
[FR] Implement Controls for imx708_noir

### ISSUE THREAD

**Issue by EdJ1** [The-EG/OctoPrint-CameraSettings#164]
**Camera manufacturer and model (ie. NexiGO N660)**:
Raspberry pi V3
It is listed as imx708_noir

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "wide_dynamic_range": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "grabbed"
  }
}

Thank you for supporting Octoprint!

**Comment by The-EG** [comment]
duplicate of #100
