### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by genehood** [The-EG/OctoPrint-CameraSettings#168]
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

I have an arducam ir camera that no longer works. I bought a new one just to see if it was the camera; the issue is still there. No display. I have done several things including changing cables several times. The cable orientation is correct.. Any ideas?

**Comment by The-EG** [comment]
This isn't an issue with this plugin and you'd be better suited asking questions on the OctoPrint forums or discord.
