### ISSUE TITLE
[FR] Implement Controls for [raspberry v3 auto focus

### ISSUE THREAD

**Issue by bstadtler** [The-EG/OctoPrint-CameraSettings#171]
**raspberry pi camera autofocus v3

{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}:

**Comment by The-EG** [comment]
duplicate of #106
