### ISSUE TITLE
[FR] Implement Controls for [Vitade HD960]

### ISSUE THREAD

**Issue by Oxize** [The-EG/OctoPrint-CameraSettings#19]
**Camera manufacturer and model (ie. NexiGO N660)**: Vitade HD960

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

{
  "zoom_continuous": {
    "type": "int",
    "min": "0",
    "max": "5",
    "step": "1",
    "default": "0",
    "value": "0"
  }
}

**Comment by Oxize** [comment]
What means the FR tag in the title. Just curious?

**Comment by The-EG** [comment]
> What means the FR tag in the title. Just curious?
Feature Request

**Comment by Oxize** [comment]
Ah cool. I am so happy this Octoprint is working out so cool with my Bresser Saurus. Bresser told, nha OctoPi doesnt work with our printers. Keep the stuff with Polarcloud. So i saw in the firmware, that the Saurus was party FlashForge. Used the 3D printer Plugin for that, and voila it was connecting after a small nano entry in the rules.

**Comment by The-EG** [comment]
Good to hear, I'm sure the OctoPrint devs would be happy to hear that (I just work on this plugin and a few other things)!

I've added 'Zoom Continuous' to the RC branch...there will be a release candidate soon.

**Comment by Oxize** [comment]
thanks, looking forward to it. Thanks for your hard work. Stay Save!

**Comment by The-EG** [comment]
This is now available in pre-release 0.1.1rc1.

You can get it now by changing to the Release Candidate channel for this plugin in the Software Update settings:
![image](https://user-images.githubusercontent.com/7342077/116700285-9aa9b800-a994-11eb-9e05-ddefe3552a5c.png)

After some testing, this will be released into an official release (0.1.1)
