### ISSUE TITLE
[FR] Implement Controls for Raspberry Pi Camera Module v3

### ISSUE THREAD

**Issue by DaveTSG** [The-EG/OctoPrint-CameraSettings#193]
**Raspberry Pi Camera Module v3**:

{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

Hello,

I have just installed a Raspberry Pi Camera Module v3 onto my RPi4B running OctoPrint v1.9.0 with Camera Settings v0.4.2. I realise the above json is kinda useless as it just contains "unknown", but that's all that was produced when I went to Settings > Camera Settings and clicked the "Copy to Clipboard" button.

In any case, I would appreciate it if support could be added for this new version of the RPi camera please.

Please let me know if you need any further information for debugging.

Thanks,
Dave

**Comment by The-EG** [comment]
Thank you. These are indeed not useful controls and will be ignored in an upcoming update.
