### ISSUE TITLE
[FR] Implement Controls for [Camera Name] Raspberry Pi Camera Module 8MP v2

### ISSUE THREAD

**Issue by xdiablo-1983x** [The-EG/OctoPrint-CameraSettings#194]
**Camera manufacturer and model (ie. NexiGO N660)**: Raspberry Pi Camera Module 8MP v2

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment]
These are not useful controls and will be ignored in an upcoming update.
