### ISSUE TITLE
[FR] Implement Controls for Benewy

### ISSUE THREAD

**Issue by Gohres94** [The-EG/OctoPrint-CameraSettings#196]
**Camera manufacturer and model (ie. NexiGO N660)**:
Benewy 1080P Full HD Webcam
**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment]
These are not useful controls and will be ignored in an upcoming update.
