### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by micha2603** [The-EG/OctoPrint-CameraSettings#199]
lesvtu 2K HD Webcam

{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

**Comment by The-EG** [comment]
duplicate, will be fixed soon
