### ISSUE TITLE
[FR] Implement Controls for Logitech QuickCam Orbit AF webcam enhancement

### ISSUE THREAD

**Issue by krafty808** [The-EG/OctoPrint-CameraSettings#20]
Would be great to the the pan/tilt & zoom function available for this webcam

**Comment by The-EG** [comment]
Hi there, as mentioned in the [FAQ](https://github.com/The-EG/OctoPrint-CameraSettings/blob/main/docs/faq.md#why-are-settings-missing-why-cant-i-control-zoom-tilt-etc):
 > The only settings shown are those that the camera reported as supported. If you get a warning that your camera has unimplemented controls then please click the link to submit an issue. Otherwise, any 'missing' controls are not shown because they are not supported by your camera.
