### ISSUE TITLE
[FR] Implement Controls for BCC950 Logitech]

### ISSUE THREAD

**Issue by coilheaddesigns** [The-EG/OctoPrint-CameraSettings#21]
{
  "pan_speed": {
    "type": "int",
    "min": "-1",
    "max": "1",
    "step": "1",
    "default": "1",
    "value": "0"
  },
  "tilt_speed": {
    "type": "int",
    "min": "-1",
    "max": "1",
    "step": "1",
    "default": "1",
    "value": "0"
  }
}

**Comment by The-EG** [comment]
This is now available in pre-release 0.1.1rc1.

You can get it now by changing to the Release Candidate channel for this plugin in the Software Update settings:
![image](https://user-images.githubusercontent.com/7342077/116700285-9aa9b800-a994-11eb-9e05-ddefe3552a5c.png)

After some testing, this will be released into an official release (0.1.1)

side note: I don't know if these will actually function or be useful, but this will remove the warning at least.
