### ISSUE TITLE
[FR] Implement Controls for [Logitech C922 Pro Stream]

### ISSUE THREAD

**Issue by Quintin9801** [The-EG/OctoPrint-CameraSettings#22]
**Camera manufacturer and model (ie. NexiGO N660)**:
Logitech C922 Pro Stream
**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "led1_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Off"
      },
      {
        "value": "1",
        "desc": "On"
      },
      {
        "value": "2",
        "desc": "Blink"
      },
      {
        "value": "3",
        "desc": "Auto"
      }
    ],
    "min": "0",
    "max": "3",
    "default": "0",
    "value": "3"
  },
  "led1_frequency": {
    "type": "int",
    "min": "0",
    "max": "255",
    "step": "1",
    "default": "0",
    "value": "24"
  }
}

**Comment by The-EG** [comment]
Oops, I missed the ref for this one. This is in commit 9b8307b589858dfaf70d301da1b46007e80846c9

It'll be in an RC release soon.

**Comment by The-EG** [comment]
This is now available in pre-release 0.1.1rc1.

You can get it now by changing to the Release Candidate channel for this plugin in the Software Update settings:
![image](https://user-images.githubusercontent.com/7342077/116700285-9aa9b800-a994-11eb-9e05-ddefe3552a5c.png)

After some testing, this will be released into an official release (0.1.1)
