### ISSUE TITLE
[BUG]  'OctoPrint-CameraSettings' requires a different Python: 2.7.16 not in '>=3, <4'

### ISSUE THREAD

**Issue by Dom1n1c** [The-EG/OctoPrint-CameraSettings#30]
I cannot install the Plugin, since it seems not to be compatible with my python version.
Could you check it?
https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

**Comment by The-EG** [comment]
This plugin is **not** compatible with Python 2, which is what the error message indicates. 

You can follow the guide you linked to upgrade your OctoPrint installation to Python 3 which will then allow you to install this plugin.
