### ISSUE TITLE
[FR] Implement Controls for [Victure AC920]

### ISSUE THREAD

**Issue by rodriguezvictor1990** [The-EG/OctoPrint-CameraSettings#36]
**Camera manufacturer and model (ie. NexiGO N660)**: Victure AC920.

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "white_balance_component_auto": {
    "type": "bool",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment]
Hi there, thanks for the report! I would have thought I had them all by now...I guess not!

This is easy to add, I'll get it in an update soon.

**Comment by The-EG** [comment]
Now in 0.2.0rc2
