### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by Super-Toaster** [The-EG/OctoPrint-CameraSettings#43]
**Camera manufacturer and model (ie. NexiGO N660)**:
Akaso V50 Pro (Action cam in webcam mode)
**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "white_balance_component_auto": {
    "type": "bool",
    "default": "0",
    "value": "0"
  }
}{
  "white_balance_component_auto": {
    "type": "bool",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment]
Per discord discussion, already addressed in #36 in 0.2.0rc3
