### ISSUE TITLE
[FR] Implement Controls for [MAXXUM - 888530]

### ISSUE THREAD

**Issue by andrewmatten** [The-EG/OctoPrint-CameraSettings#44]
**Camera manufacturer and model (MAXXUM - 888530)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

{
  "white_balance_red_component": {
    "type": "int",
    "min": "0",
    "max": "255",
    "step": "0",
    "default": "128",
    "value": "128"
  },
  "white_balance_blue_component": {
    "type": "int",
    "min": "0",
    "max": "255",
    "step": "1",
    "default": "128",
    "value": "128"
  },
  "iris_absolute": {
    "type": "int",
    "min": "0",
    "max": "0",
    "step": "0",
    "default": "0",
    "value": "0"
  },
  "iris_relative": {
    "type": "int",
    "min": "0",
    "max": "0",
    "step": "0",
    "default": "0",
    "value": "0",
    "flags": "write"
  }
}

**Comment by The-EG** [comment]
These should already be in 0.2.0 which I just released. If not, let me know!
