### ISSUE TITLE
Onebuy Webcam cheap Amazon webcam

### ISSUE THREAD

**Issue by Zardoz66** [The-EG/OctoPrint-CameraSettings#5]
[octoprint-2.log](https://github.com/The-EG/OctoPrint-CameraSettings/files/6328089/octoprint-2.log)
no controls working also missing.

**Comment by The-EG** [comment]
'also missing' as in missing controls? Please paste the data from the 'copy to clipboard' if so.

**Comment by The-EG** [comment]
from discord chat: camera controls not missing, just don't work. this will be a duplicate of #4 I think.
