### ISSUE TITLE
[FR] Support preview when using HLS stream type

### ISSUE THREAD

**Issue by pandel** [The-EG/OctoPrint-CameraSettings#53]
Hi!

I am using your plugin with the newest OctoPi release and set "camera_streamer=hls" (octopi.txt). This gives a much better video performance in my network and lower overall system load.

Sadly, the stream is not shown in the preview area of your plugin. Would be nice, if you'd take look at this...

Thanks, stay safe!

Regards,
Holger

**Comment by The-EG** [comment]
I'll have to review this to see how OctoPrint deals with the HLS stream. The plugin doesn't know or even care what program is streaming or what type of stream it is. The preview is just showing the same URL that's configured in OctoPrint but I suspect there must be something a bit different going on there to work with HLS.

**Comment by pandel** [comment]
Thanks! I was wondering also about why the stream is not showing up. I looked through your code, but did not find anything special that could perhaps prevent it...

I made a test: I copied the HTML tag from UI customizers video frame via the browser console to your plugin view and replaced the existing img tag with:

`<video muted="" autoplay="" style="width: 100%" src="/hls/stream.m3u8"></video>`

That did the trick ;-) - video is shown.

**Comment by The-EG** [comment]
Good to know you can just put it in a video tag. The problem is the plugin has to have a way of knowing the stream should be hls. I may just put in a generic option to use a video element instead of a img.

**Comment by The-EG** [comment]
> That did the trick ;-) - video is shown.

Which browser are you using? Just using a video tag doesn't work in my environment:
![image](https://user-images.githubusercontent.com/7342077/132948710-0f2d3c15-630b-4af4-bf1e-f09681f11a4e.png)
![image](https://user-images.githubusercontent.com/7342077/132948718-3f66cf30-f633-422b-a9b3-8fb676fc1e87.png)

Do you also have a plugin installed to change the main OctoPrint camera view to HLS? It may be doing more than just that...

**Comment by pandel** [comment]
I am using Safari on Mac OS.

No, I don't used any plugin. I changed the `camera_streamer`option in octopi.txt and rebooted the Pi. After that, I only changed some values in `/etc/systemd/system/ffmpeg_hls.conf` regarding resultion, etc. . In Octoprint, I set the stream source to `hls/stream.m3u8`.

Via browser console, I changed the your img element to this:
`<video muted="" autoplay="" style="width: 100%" src="/hls/stream.m3u8"></video>`

**Comment by The-EG** [comment]
Ok, it's sounding like support various across different browsers. This is going to take more effort than just a video tag, unfortunately.

**Comment by The-EG** [comment]
Ok, I poked around at how OctoPrint is supporting HLS streams and I've replicated the same thing...this should work for any browser that the main 'Control' view with HLS streams currently works with.

Please try it out, install this plugin with this URL https://github.com/The-EG/OctoPrint-CameraSettings/archive/refs/heads/fr/hls-preview.zip

I'll get this into an RC soon and hopefully get some more people to test it too.

**Comment by The-EG** [comment]
Fix now available in 0.3.0rc1
