### ISSUE TITLE
[BUG] Focus Absolute not applied at startup (Logitech C920)

### ISSUE THREAD

**Issue by S7EN** [The-EG/OctoPrint-CameraSettings#54]
**Observed behavior**
Focus Absolute Settings get not saved

**Expected behavior**
Should be saved

**OctoPrint Version**
Latest

**CameraSettings Plugin Version**
Latest

**Camera**
Logitech C920

**Linux/OctoPi**
OctoPi latest

**Other Plugins**
No

**Comment by The-EG** [comment]
When you say 'not saved' do you mean it's not taking affect or it's not saving in the preset?

**Comment by S7EN** [comment]
When i saved the settings and restart the pi the focus absolute is 0 again. Tried to delete the preset and reinstalled the plugin but it takes no effect.

**Comment by The-EG** [comment]
Increment `'Startup Preset Apply Count` and try it again.

See https://github.com/The-EG/OctoPrint-CameraSettings/blob/main/docs/faq.md#not-all-settings-are-applied-on-on-startup

**Comment by S7EN** [comment]
Ah okay, didn`t know about the faq and solution. That worked, thanks.

**Comment by The-EG** [comment]
> Ah okay, didn`t know about the faq and solution. That worked, thanks.

No problem, I'm glad that's all it was, and thanks for confirming!
