### ISSUE TITLE
[FR] Implement Controls for Microsoft LifeCam HD-3000

### ISSUE THREAD

**Issue by BlueWings172** [The-EG/OctoPrint-CameraSettings#55]
Hello

Just installed this plugin and I can't find any settings to control. I have Octoprint on Docker (IOTstack).

Is this plugin compatible with Docker ? Is the issue that my webcam model (Microsoft LifeCam HD-3000) not supported?

![Octoprint screenshot](https://user-images.githubusercontent.com/65966061/135002578-46906e1e-63ef-424c-8e9b-084815d36924.jpg)

This is what is see on the plugin page on Octoprint. Stream loads fine but the dropdown menu next it does not show any items when I click on it and there are no settings to control.

I would appreciate any help.

Thanks

**Comment by The-EG** [comment]
Hi there, I'm not sure about the compatibly with docker, but in general the environment that OctoPrint runs in would need to have access to the camera. Specially, if the applicable `/dev/videoN` device isn't available

**Comment by The-EG** [comment]
Also, your camera should work. In addition to the device I mentioned above, the plugin looks at some specific sysfs files to look for the camera names, so they'd have to be available too.

**Comment by BlueWings172** [comment]
> Hi there, I'm not sure about the compatibly with docker, but in general the environment that OctoPrint runs in would need to have access to the camera. Specially, if the applicable `/dev/videoN` device isn't available then the plugin won't work.

Octoprint does already have access to my camera and the camera works well with plugins like Octolapse and Sidebar Webcam. 
In the screenshot I have included above, you can see the webcam streaming.

**Comment by The-EG** [comment]
No, OctoPrint only needs access to the camera *URL* for those things to work. This plugin works independently of the steamer program, and so the the OctoPrint process needs access to the actual camera device at the operating system level.

Running OctoPrint in a docker container had likely isolated it away from that access and resolving that is outside of the scope of this plugin or what I can help with.
