### ISSUE TITLE
[FR] Switch IR cut filter for Night Vision IR Cut Video Cameras

### ISSUE THREAD

**Issue by FrankGBusch** [The-EG/OctoPrint-CameraSettings#59]
Hi,

I'm using a Night Vision IR Cut Video Camera connected to the camera slot on the Pi board. It would be awesome if the IR filter activation or deactivation of this camera can be configed directly in the camera settings.

CheersF.

**Comment by FrankGBusch** [comment]
I think I found this command lines in a raspberry forum (can't remember where ...), but no additional wires, it was all done via the default camera connector on the board. 

Meanwhile I replaced the camera with another one which automatically switches between day and night mode based on the brigthness. So OctoPrint together with the camera now works exactly as I had imagined.

**Comment by The-EG** [comment]
Closing this since I don't have a camera for testing and you've found a different solution. If other users end up wanting something similar, this can be revisited in the future.
