### ISSUE TITLE
[UI] Settings do not scroll independently of camera preview

### ISSUE THREAD

**Issue by The-EG** [The-EG/OctoPrint-CameraSettings#6]
This may be due to UI Customizer:
![image](https://user-images.githubusercontent.com/7342077/115144752-69d49500-a01c-11eb-9f4a-3d09d193162b.png)

**Comment by The-EG** [comment]
This is an issue with UI Customizer.

**Comment by LazeMSS** [comment]
Just a couple of notes - this should be removed:

https://github.com/The-EG/OctoPrint-CameraSettings/blob/abd806f8487a2b4259467d1c638684618f49b3ad/octoprint_CameraSettings/templates/camerasettings_settings.jinja2#L3
```
{% assets "js_client" %}
<script src="{{ url_for("static", filename="js/lib/jquery/jquery.min.js") }}"></script>
<script src="{{ url_for("static", filename="js/lib/lodash.min.js") }}"></script>
<script type="text/javascript" src="{{ url_for("static", filename="webassets/packed_client.js") }}"></script>
{% endassets %}
```

**Comment by The-EG** [comment]
> Just a couple of notes - this should be removed:
> 
> https://github.com/The-EG/OctoPrint-CameraSettings/blob/abd806f8487a2b4259467d1c638684618f49b3ad/octoprint_CameraSettings/templates/camerasettings_settings.jinja2#L3

Thanks! Yes, I removed that when we were talking about it the other day (and also from my other plugin where it go copied from): 44c06502227850efdf2e448b8b84ff387c475990

**Comment by The-EG** [comment]
Should be fixed or at least improved in UI Customizer now.
