### ISSUE TITLE
[FR] Implement Controls for Raspberri Pi camera v2

### ISSUE THREAD

**Issue by erripe13** [The-EG/OctoPrint-CameraSettings#62]
**Camera manufacturer and model (ie. NexiGO N660)**:
Raspberry pi camera v2

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "force_key_frame": {
    "type": "button",
    "flags": "write"
  },
  "h264_minimum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "h264_maximum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment]
These controls are now available for testing in version 0.3.1rc2.

You can update to that by selecting the Release Candidate channel for this plugin:
![image](https://user-images.githubusercontent.com/7342077/143782096-5090a50b-cb6c-445a-9239-804a8dd78aa9.png)

**Comment by erripe13** [comment]
Working ! 😄
