### ISSUE TITLE
[FR] Implement Controls for Logitech quickcam orbit/sphere

### ISSUE THREAD

**Issue by klpgo** [The-EG/OctoPrint-CameraSettings#67]
**Camera manufacturer and model (ie. NexiGO N660)**:
Logitech quickcam orbit/sphere (old Camera, it would be awesome to get help)
**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "pan_relative": {
    "type": "int",
    "min": "-4480",
    "max": "4480",
    "step": "0",
    "default": "0",
    "value": "0",
    "flags": "write"
  },
  "tilt_relative": {
    "type": "int",
    "min": "-1920",
    "max": "1920",
    "step": "0",
    "default": "0",
    "value": "0",
    "flags": "write"
  },
  "pan_reset": {
    "type": "button",
    "flags": "write"
  },
  "tilt_reset": {
    "type": "button",
    "flags": "write"
  }
}

**Comment by The-EG** [comment]
![image](https://user-images.githubusercontent.com/7342077/151601032-8fe4a21d-0f8d-4d47-96b7-55a12d59a8cd.png)

Hi there...these look really familiar. I thought I had implemented this already, but they definitely aren't in the source code.
