### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by king-of-styx** [The-EG/OctoPrint-CameraSettings#68]
**Camera manufacturer and model (ie. NexiGO N660)**:
Logitech, Inc. QuickCam Orbit/Sphere AF
Device ID 046d:0994
**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "pan_relative": {
    "type": "int",
    "min": "-4480",
    "max": "4480",
    "step": "0",
    "default": "0",
    "value": "0",
    "flags": "write"
  },
  "tilt_relative": {
    "type": "int",
    "min": "-1920",
    "max": "1920",
    "step": "0",
    "default": "0",
    "value": "0",
    "flags": "write"
  },
  "pan_reset": {
    "type": "button",
    "flags": "write"
  },
  "tilt_reset": {
    "type": "button",
    "flags": "write"
  }
}

**Comment by The-EG** [comment]
duplicate of #50 , #46
