### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by pohromashka** [The-EG/OctoPrint-CameraSettings#70]
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "mpeg_2_slice_parameters": {
    "type": "unknown"
  },
  "mpeg_2_quantization_matrices": {
    "type": "unknown"
  },
  "h264_sequence_parameter_set": {
    "type": "unknown"
  },
  "h264_picture_parameter_set": {
    "type": "unknown"
  },
  "h264_scaling_matrix": {
    "type": "unknown"
  },
  "h264_slice_parameters": {
    "type": "unknown"
  },
  "h264_decode_parameters": {
    "type": "unknown"
  },
  "h264_decode_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Slice-Based"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  },
  "h264_start_code": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "No Start Code"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  },
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "hevc_slice_parameters": {
    "type": "unknown"
  },
  "hevc_decode_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Slice-Based"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  },
  "hevc_start_code": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "No Start Code"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment]
Hey there, what kind of camera is this? It's not essential, but I like to know for historical purposes and it gives me an idea of all the different kinds of cameras that work with the plugin.
