### ISSUE TITLE
Can't add plugin

### ISSUE THREAD

**Issue by imawizzard** [The-EG/OctoPrint-CameraSettings#73]
Hello,

I can't find the plugin in the plugin manager.
When I download the zip file and upload it, it doesn't show up in the plugins.

![afbeelding](https://user-images.githubusercontent.com/41449816/164979175-743e26bd-0526-416c-9324-9aa0a464b62e.png)

**Comment by The-EG** [comment]
The plugin manager won't show it if it's not compatible with your setup and even if you manually install it, it still won't work. It requires Python 3 and Linux.

**Comment by imawizzard** [comment]
I used the plugin in the past, why should it not work with my setup? i only
have multicam

Op zo 24 apr. 2022 17:28 schreef Taylor Talkington ***@***.***

**Comment by The-EG** [comment]
Well, you've told me absolutely nothing about your setup so I can only guess. If you have filled out the bug report template instead of deleting it or starting with a fresh issue I could have some idea...

so, lets start there:

> **Observed behavior**
> What is happening or not working?
> 
> **Expected behavior**
> What should be happening?
> 
> **OctoPrint Version**
> What version of OctoPrint are you using?
> 
> **CameraSettings Plugin Version**
> What version of this plugin are you using?
> 
> **Camera**
> What camera are you using?
> 
> **Linux/OctoPi**
> What Linux distribution/image is this running on? If you are unsure, it is probably OctoPi. If OctoPi, what version?
> 
> **Other Plugins**
> Do you have any other plugins that may be modifying the camera stream (ie, The Spaghetti Detective)?
> 
> 
>

**Comment by imawizzard** [comment]
Observed behavior
    Can't install the Camera Settings Plugin

    Expected behavior
   Install the plugin

    OctoPrint Version
    What version of OctoPrint are you using?
1.7.3
    CameraSettings Plugin Version
    What version of this plugin are you using?
Latest (0.3.2)
    Camera
    What camera are you using?
Trust Trino 720P, Endoscope
    Linux/OctoPi
    What Linux distribution/image is this running on? If you are unsure, it is probably OctoPi. If OctoPi, what version?
0.18.0
    Other Plugins
    Do you have any other plugins that may be modifying the camera stream (ie, The Spaghetti Detective)?
![afbeelding](https://user-images.githubusercontent.com/41449816/164992328-17b4603d-d63b-46bd-b0fc-a7007e739aba.png)
![afbeelding](https://user-images.githubusercontent.com/41449816/164992331-8eabbe42-7562-4275-a159-200ad9864652.png)

**Comment by imawizzard** [comment]
[octoprint.log](https://github.com/The-EG/OctoPrint-CameraSettings/files/8550339/octoprint.log)

**Comment by The-EG** [comment]
from your octoprint.log:
> 2022-04-24 19:41:41,660 - octoprint.plugin.core - INFO - 33 plugin(s) registered with the system:
> ...
> | !Camera Settings (0.3.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_CameraSettings
> ...
> Prefix legend: ! = disabled, # = blacklisted, * = incompatible

It's installed, you have it disabled.

**Comment by imawizzard** [comment]
Didn't know that. I Will check it.

Thank you

Op ma 25 apr. 2022 15:04 schreef Taylor Talkington ***@***.***
