### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by GreetingsGQ** [The-EG/OctoPrint-CameraSettings#78]
Argmao 1080P HD Webcam with Microphone for Desktop
https://amazon.com/dp/B09JZL2XX4

{
  "min_number_of_capture_buffers": {
    "type": "int",
    "min": "1",
    "max": "32",
    "step": "1",
    "default": "1",
    "value": "1",
    "flags": "read"
  }
}

**Comment by The-EG** [comment]
Sorry for the delay, this is now available in 0.4.1rc1. You can try this version out by switching to the 'Release Candidate' channel for this plugin in the Software Updates section of OctoPrint's settings.
