### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by Tinkergnome621** [The-EG/OctoPrint-CameraSettings#79]
**Camera manufacturer and model (ie. NexiGO N660)**:
Arducam 16MP Autofocus Camera for Raspberry Pi and Nvidia Jetson Nano/NX

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

{
  "frame_rate": {
    "type": "int",
    "min": "1",
    "max": "30",
    "step": "1",
    "default": "30",
    "value": "10"
  }
}

**Comment by The-EG** [comment]
Sorry for the delay, this is now available in 0.4.1rc1. You can try this version out by switching to the 'Release Candidate' channel for this plugin in the Software Updates section of OctoPrint's settings.
