### ISSUE TITLE
[FR] Implement Controls for [Arducam 8MP IMX219 175 Degree Ultra Wide Angle Raspberry Pi Camera Module]

### ISSUE THREAD

**Issue by cTurtle98** [The-EG/OctoPrint-CameraSettings#81]
**Camera manufacturer and model (ie. NexiGO N660)**:
Arducam 8MP IMX219 175 Degree Ultra Wide Angle Raspberry Pi Camera Module
https://www.amazon.com/gp/product/B09VSVB4DT

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "link_frequency": {
    "type": "intmenu",
    "values": [
      {
        "value": "0",
        "desc": "456000000 (0x1b2e0200)"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0",
    "flags": "read"
  }
}

**Comment by The-EG** [comment]
I'm not real sure why camera devs keep implementing 'new' controls that have no use like this one...but it has been added so at least the warning goes away.

Now in 0.4.1rc2
