### ISSUE TITLE
[FR] Implement Controls for jetson nano camera

### ISSUE THREAD

**Issue by alexian79** [The-EG/OctoPrint-CameraSettings#87]
Hi this is jetson nano camera imx219, Thank you.

**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "group_hold": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "execute"
  },
  "sensor_mode": {
    "type": "int64",
    "min": "0",
    "max": "6",
    "step": "1",
    "default": "0",
    "value": "0",
    "flags": "slider"
  },
  "frame_rate": {
    "type": "int64",
    "min": "2000000",
    "max": "21000000",
    "step": "1",
    "default": "21000000",
    "value": "21000000",
    "flags": "slider"
  }
}

**Comment by The-EG** [comment]
Hi there, sorry for the delay. I plan to add these and then publish a new release this weekend!

**Comment by alexian79** [comment]
Thank you, not pushing here, just a humble request :)
