### ISSUE TITLE
Implement Controls for Avermedia PW513

### ISSUE THREAD

**Issue by Alldayallan** [The-EG/OctoPrint-CameraSettings#88]
**Camera manufacturer and model: Avermedia PW513

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste he{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  },
  "hevc_decode_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Slice-Based"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  },
  "hevc_start_code": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "No Start Code"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  }
}re)**:

**Comment by The-EG** [comment]
Hi there, these should already be available in the latest release candidate. It has been hanging out there for a while, but I do plan to push it to a full release soon. If you want to try it out before then, go to Software Update in OctoPrint Settings and select the Release Candidate channel for this plugin.
