### ISSUE TITLE
Cant take snapshot after update 0.4.1

### ISSUE THREAD

**Issue by Ricky0351** [The-EG/OctoPrint-CameraSettings#92]
since the update: the camera is working in octoprint. but at the end of the print the plugin "Print Job History" is taking a snapshot, but it cant, and after that the camera is disabled and not working anymore.

**Comment by Ricky0351** [comment]
PJH:ERROR: Take Snapshot
Unable to get snapshot from URL: http://127.0.0.1:8080/?action=snapshot

**Comment by The-EG** [comment]
Sorry to hear that, but this plugin does not alter any of the camera streaming/snapshot settings.
Verify that you haven't changed any of those settings yourself and that the camera is still functioning otherwise.
