### ISSUE TITLE
[FR] Implement Controls for Arducam 8MP IMX219

### ISSUE THREAD

**Issue by darthtate** [The-EG/OctoPrint-CameraSettings#96]
{
  "hue_automatic": {
    "type": "bool",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment]
This should now be available in the latest release candidate. Directions for installing that are available in the FAQ: https://github.com/The-EG/OctoPrint-CameraSettings/blob/main/docs/faq.md#how-do-i-install-the-latest-release-candidate
