### ISSUE TITLE
[FR] Implement Controls for [Raspberry Pi V2 Camera Module]

### ISSUE THREAD

**Issue by abit11w** [The-EG/OctoPrint-CameraSettings#97]
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment]
Please upgrade to the latest version, these 'unknown' controls are now ignored.
