### ISSUE TITLE
[FR] Implement Controls for [Logitec c920]

### ISSUE THREAD

**Issue by HoCoOhNo** [The-EG/OctoPrint-CameraSettings#99]
**Camera manufacturer and model (Logitec c920)**:

**Unknown controls information ({
  "ipu3_pipe_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Video mode"
      },
      {
        "value": "1",
        "desc": "Still mode"
      }
    ],
    "min": "0",
    "max": "1",
    "default": "0",
    "value": "0"
  }
}
)**:

**Comment by The-EG** [comment]
This should now be available in the latest release candidate. Directions for installing that can be found in the FAQ: https://github.com/The-EG/OctoPrint-CameraSettings/blob/main/docs/faq.md#how-do-i-install-the-latest-release-candidate
